- name: Check if image is present
  shell: "lxc image ls --format=json | grep {{ lxd_image.split (':')[1] if lxd_image.split (':') | length > 1 else lxd_image }}"
  register: image_status
  changed_when: image_status.stdout == ""
  delegate_to: "{{ pve_primary_host_ip }}"
  become: yes

- name: Download image and set attributes
  shell: "lxc image copy {{ lxd_image }} local: --auto-update={{ lxd_image_autoupdate }} {{ '--alias='+ lxd_image_alias if lxd_image_alias is defined else None }}"
  delegate_to: "{{ pve_primary_host_ip }}"
  when: image_status.changed
  become: yes

- name: "Create container for {{ lxd_hostname }}"
  shell: "lxc launch {{ lxd_image }} {{ lxd_hostname }}"
  register: response
  delegate_to: "{{ pve_primary_host_ip }}"
  become: yes

# - name: 'Wait for container create'
#   async_status:
#     jid: "{{ response.ansible_job_id }}"
#   register: job_result
#   until: job_result.finished
#   retries: 10
#   delegate_to: "{{ pve_primary_host_ip }}"
