- name: Install necessary packages
  apt:
    name:
      - zfsutils-linux
      # becuase of vxlan over unicast
      # https://lxadm.com/Unicast_VXLAN:_overlay_network_for_multiple_servers_with_dozens_of_containers
      - bridge-utils
      - ebtables


- name: Proxmox Setup | Gather facts about zfs
  zpool_facts: properties='free,size'
  register: zpool_facts
  tags:
    - zfs
    - shared_directory

- name: Remap zfs_pools
  set_fact:
    zpools: "{{ zpools | default ([]) | combine ( {item.name : item }) }}"
  with_items: "{{ zpool_facts.ansible_facts.ansible_zfs_pools }}"
  tags:
    - zfs
    - shared_directory

- debug:
    var: zpools
  tags:
    - zfs
    - shared_directory


- name: Check block device exists
  stat:
    path: "{{ item }}"
  register: zpool_block
  loop: zpool_block_device

- debug:
    var: zpool_block

- name: Create zpool as container storage
  shell: "zpool create -f -o failmode=continue -o ashift=12 {{ zpool_name }} {{ zpool_block_device | join (' ')}}"
  when: "'zpool_name' not in zpools"
  become: yes

- name: Init lxd
  shell: "lxd init --preseed {{ lookup ('template', 'lxd_preseed.j2')}}"
  become: yes

- name: Add ubuntu Minimal LXD repository with cloud-init enabled
  shell: "lxc remote add --protocol simplestreams ubuntu-minimal https://cloud-images.ubuntu.com/minimal/releases/"

# - name: Create container for lxdMosaic
#   import_role:
#     name: lxd_container_create
#   vars:
#     lxd_image: ubuntu-minimal:bionic
#     lxd_image_autoupdate: true
#     lxd_hostname: lxdMosaic
#
# - name: Download installation source of mosaic into container
#   command: lxc exec lxdMosaic -- /bin/bash -c "curl -s https://raw.githubusercontent.com/turtle0x1/LxdMosaic/master/examples/install_with_clone.sh >> installLxdMosaic.sh && chmod +x installLxdMosaic.sh"
#   become: yes
#
# - name: Install LXD mosaic
#   command: lxc exec lxdMosaic -t -- /root/installLxdMosaic.sh
#   register: output
#
# - debug:
#     var: output
#
# - name: Open lxdMosaic to public IP
#   command: lxc config device add lxdMosaic  www proxy listen=tcp:0.0.0.0:8080 connect=tcp:127.0.0.1:443
#
# - name: Open lxdMosaic to public IP
#   command: lxc config device add lxdMosaic www-api proxy listen=tcp:0.0.0.0:30000 connect=tcp:127.0.0.1:3000

#sudo lxc image copy  images:alpine/3.11 local: --alias alpine
#lxc launch ubuntu-minimal:focal

# Profile remap user
#   raw.idmap: |
#     uid $_UID 1000
#     gid $GID 1000
#
# adduser -u 1000 -s /bin/ash -h /home/domains/motvmw www-data
#
# remap user (https://gist.github.com/bloodearnest/ebf044476e70c4baee59c5000a10f4c8)
#

#lxc config device add lxdMosaic web proxy listen=tcp:0.0.0.0:443 connect=tcp:127.0.0.1:443
